<?php

namespace app\models;
use yii\db\ActiveRecord;


class ServiceOrder extends ActiveRecord{

    public static function tableName()
    {
        return 'service_order'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name_service', 'description', 'company', 'place', 'address','user_id','status_id'], 'required']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'            => 'ID',
            'name_service'  => 'Name_service',
            'description'   => 'Description',
            'company'       => 'Company',
            'place'         => 'Place',
            'address'       => 'Address',
            'status_id'     => 'Status_id',
            'user_id'       => 'User_id',
        ];
    }


}

?>